url: https://ensinopmg.com.br
baseurl: /

# Site settings
title: EnsinoPMG
email: contato@ensinopmg.com.br
description: "Agencia de aulas particulares com professores qualificados minuciosamente selecionados."


# Team names, titles and social links
people:
- name: Patricia Monteiro
  pic: 1
  position: CEO

- name: Ezequiel Bertti
  pic: 2
  position: Desenvolvedor
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Tatiana Gigante
  pic: 3
  position: Financeiro

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ensinopmg
  - title: facebook
    url: https://facebook.com/ensinopmg
  - title: istagram
    url: https://instagram.com/ensinopmg

# Postal address (add as many lines as necessary)
address:
  - line: Av das Américas, Barra da Tijuca
  - line: Rio de Janeiro, RJ, Brasil

# Build settings
markdown: kramdown
permalink: pretty